### ISSUE TITLE
Understand and explain part in more depth (LED)

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#30]
@YingzhuoYang

**Comment by YingzhuoYang** [comment]
[DSAZIHA2X000148723.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8082179/DSAZIHA2X000148723.pdf)
[1001datasheet.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8082180/1001datasheet.pdf)

**Comment by YingzhuoYang** [comment]
[max7219-max7221-1178406.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8121544/max7219-max7221-1178406.pdf)
[DSAZIHA2X000148723.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8121545/DSAZIHA2X000148723.pdf)

**Comment by YingzhuoYang** [comment]
Quadruple Digit Numeric Displays: 

Part #: KW4-56NCWB-P-Y
It’s a 7-segment 4 digits display with four dots and one colon in the middle, which makes it perfect for display time and perfect for our project. 

The display has maximum forward current of 25 mA and typical forward voltage of 3.2V (4V max). To use this display, we must also connect it to a display driver which we use MAX7219ENG in particular.

The part has 7 pins on each side which is 14 pins in total. Pins 13, 9, 4, 2, 1, 12, 5, and 3 correspond to 7 segments A, B, C, D, E, F, and G separately. Pin 7 controls the colon and pins 14, 11, 10, and 6 controls which 4 digits is displaying. 

Since the display can only shows one digits at once, to show all 4 digits at the same time, we must switch cycle between 4 pins in a very short time, for example 10ns.

**Comment by YingzhuoYang** [comment]
Quadruple Digit Numeric Displays: 

Part #: KW4-56NCWB-P-Y
It’s a 7-segment 4 digits display with four dots and one colon in the middle, which makes it perfect for display time and perfect for our project. 

The display has maximum forward current of 25 mA and typical forward voltage of 3.2V (4V max). To use this display, we must also connect it to a display driver which we use MAX7219ENG in particular.

The part has 7 pins on each side which is 14 pins in total. Pins 13, 9, 4, 2, 1, 12, 5, and 3 correspond to 7 segments A, B, C, D, E, F, and G separately. Pin 7 controls the colon and pins 14, 11, 10, and 6 controls which 4 digits is displaying. 

Since the display can only shows one digits at once, to show all 4 digits at the same time, we must switch cycle between 4 pins in a very short time, for example 10ns. 
<img width="702" alt="Screen Shot 2022-02-22 at 23 21 58" src="https://user-images.githubusercontent.com/98344909/155261309-232d0de3-d165-424b-92cf-c40333edba2b.png">

<img width="593" alt="Screen Shot 2022-02-22 at 23 22 22" src="https://user-images.githubusercontent.com/98344909/155261334-d031cc10-a58a-481b-b40e-c01368d125b5.png">
